
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_rent?createDatabaseIfNotExist=true
    username: root
    password: Sohrab@78692
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#  application:
#    name: rent
#server:
#  port: 8181

hystrix:
  timeout: 1000
